language: node_js
node_js:
  - 'lts/*'

install:
  - npm install
  # - npm run posttest
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: enigmator-api
    skip_cleanup: true
    on:
      all_branches: true
    bucket: enigmator-storage
    region: eu-west-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: enigmator-storage
    key: latest.zip
    bundle_type: zip
    application: enigmator
    deployment_group: DeployEnigmator
    region: eu-west-3
    on:
      all_branches: true

script:
  - zip -r latest *
  - mkdir -p enigmator-api
  - mv latest.zip enigmator-api/latest.zip

notifications:
  email:
    recipients:
      - loic.colat@gmail.com
    on_success: never
    on_failure: always
