language: node_js
node_js:
  - 'lts/*'

install:
  - npm install
  - npm run posttest

notifications:
  email:
    recipients:
      - loic.colat@gmail.com
    on_success: never
    on_failure: always
